### PR TITLE
Update ibm_cloud_power gem

### PR DESCRIPTION
**Pull request by jaywcarman**
Marking WIP until I have a chance to do some validation.

### CODE REVIEW

**Comment by jaywcarman** [comment]
@agrare these are the power cloud updates using the upstream OpenAPI generator. I did a quick local test of some of the new APIs and everything worked.

**Comment by agrare** [comment]
Looks good to me @jaywcarman LMK when you're ready

**Comment by agrare** [comment]
@jaywcarman I just ran a quick test with this and the manageiq powervs provider refresher spec and am getting this error:
```
  4) ManageIQ::Providers::IbmCloud::PowerVirtualServers::CloudManager::Refresher#refresh refreshes the child storage_manager
     Failure/Error: @networks ||= networks_api.pcloud_networks_getall(cloud_instance_id).networks || []
     
     ArgumentError:
       invalid value for "type", must be one of ["vlan", "vxlan"].
```

I had manually patched the spec prior to sdk generation to fix this pending a proper fix, looks like we still need to do that

**Comment by jaywcarman** [comment]
> @jaywcarman I just ran a quick test with this and the manageiq powervs provider refresher spec and am getting this error:

Nice catch @agrare. I force pushed an update with the `pub-vlan` network type included. Specs now pass in `manageiq-providers-ibm_cloud`.

**Review by agrare — APPROVED** [review]

**Comment by agrare** [comment]
Released v1.1.0

**Pull request merged**
