### PR TITLE
Add ibm-derived resource manager gem

### PR DESCRIPTION
**Pull request by jaredm-ibm**
# Description
Adds IBM-derived resource manager sdk https://cloud.ibm.com/apidocs/resource-controller/resource-manager. Used in VPC provision.

# Priority
Required to add provisioning to IBM VPC plugin. Need to wait for VPC SDK to be published by IBM.

# Implementation
Use IBM tools to generate Resource Manager API access from https://cloud.ibm.com/apidocs/resource-controller/resource-manager.json.

# Not covered
* Resource Controller https://cloud.ibm.com/apidocs/resource-controller/resource-controller API is not added .

# Spec
* No specs created.

# Common files
* No common files changed.

### CODE REVIEW

**Comment by agrare** [comment]
So we discussed in a PM but just to summarize:
1. We want new APIs to use the openapi-sdkgen tool (:heavy_check_mark: here)
2. We want to group APIs logically by their api group (in this case resource_controller has resource_controller_v2 and and resource_manager_v2)
3. This means we'll need to "upgrade" the current `ibm_cloud_resource_controller` to the new format, push a major gem version (breaking change), update the ibm-cloud-powervs provider to use the new format, then add the resource_manager_v2 to it

**Comment by jaredm-ibm** [comment]
I'm fine with updating and combining gems. Hopefully, that should simplify our requirements in the provider. The question is when can this get done? I need a list of available resource groups for VPC provisioning. I can work on volumes for now, but those also need resource groups.

**Comment by agrare** [comment]
Okay lets replace the existing resource_controller gem (https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/tree/master/gems/ibm_cloud_resource_controller) with this one, do a major version bump, and add an `openapi-sdkgen` generated `resource_controller/resource_controller_v2` api

**Comment by jaredm-ibm** [comment]
Closing. No longer needed.

**Pull request closed without merging**
